FROM tomcat
RUN apt update -y
ADD http://13.232.51.31:8081/nexus/service/local/repositories/releases/content/com/wakaleo/gameoflife/gameoflife/1.0/gameoflife-1.0.war /root
RUN rm -rf  /usr/local/tomcat/webapps/ROOT
RUN cp /root/gameoflife-1.0.war /usr/local/tomcat/webapps/ROOT.war