FROM tomcat
RUN apt update -y
ADD http://13.233.227.127:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=com.wakaleo.gameoflife&a=gameoflife&p=war&v=LATEST /root
RUN rm -rf  /usr/local/tomcat/webapps/ROOT
RUN cp /root/gameoflife-1.0.war /usr/local/tomcat/webapps/ROOT.war
RUN docker build -t tomcatimage . 
RUN docker run -itd --name ci-cd-container -p 6060:6060 tomcatimage
